### PR TITLE
Feature/theme switch

### PR DESCRIPTION
**Pull request by thomas-desmond**

### CODE REVIEW

**Review by dylanyoung-dev — CHANGES_REQUESTED** [review]
Overall everything here makes sense.  You added an additional provider, which considering the limited scenarios for storing state at the parent level, I think that makes sense.  Using the Context API makes the most sense to do that, but I will note I have been wondering when we'll hit a point where we might need to handle app state differently.  But I believe we are at that threshold but not beyond it.  So continuing with this approach I think is fine.  Removing from GameInfoContext, into it's own, makes sense here, because it wasn't needed in Game Info Context any longer.

Only two comments, 1) above about the comment should be remove and 2) this needs to be finalized from a visual.  Not just the picker, but when I switch to fantasy, some of the elements (around the avatar + Persona) are still in corporate view with some fantasy on top.

**Comment by dylanyoung-dev** [comment]
I think you mentioned that you wanted me to look at this @thomas-desmond, but I see there are some conflicts.  So just ping me when you want me to review again.

**Comment by thomas-desmond** [comment]
Thanks for the reminder @dylanyoung-dev. 

I think I addressed the issues you brought up. I got rid of everything for the Corporate elements still showing up in the fantasy theme. I took out the extra oval card where the persona title was left over. Was there anything else?

**Review by dylanyoung-dev — APPROVED** [review]
Went through a few times and really couldn't locate any issues besides those merge issues that have been resolved.  Looks good on my end.

**Pull request merged**
