### PR TITLE
Feature/cdp integration

### PR DESCRIPTION
**Pull request by dylanyoung-dev**
For this PR, the following changes were made:

- Created a new UseContext provider for Engage Tracker (so we can globally track page views or custom events).  Initially, we are tracking page views and all the prompt pages that load, and the id of the prompt page.  Also tracking when someone changes the theme, avatar, or persona as custom events.
    - With that, there is a new custom hook called useEngageTracker, which you can make requests to in any functional components (Hook rules) to add custom events or track page view events.
- Moved the GameInfoContext to a new components/Context folder, alongside the Context for Engage.
- Made the necessary adjustments for GameInfoContext

** Note: Need to implement a cookie notice/disclaimer

### CODE REVIEW

**Comment by thomas-desmond** [comment]
A few questions/comments I've got here. 

1. The following code snippet is from `PromptPanel.tsx`

```
      if (currentPrompt !== undefined) {
        setCurrentPrompt(currentPrompt);

        await tracker.TrackPageView(
          { page: '/prompts', channel: 'WEB', language: 'EN', currency: 'USD' },
          { prompt: currentPrompt?.id }
        );
```

We have had issues in the past pop-up because `setCurrentPrompt()` is not asynchronous. This looks like one of those scenarios where we are not guaranteeing that `currentPrompt` was indeed updated. 


2. This is more because I don't know CDP well enough, but is the tracking turned off for dev/staging environment? Ideally we only track production events. Especially if we start running automated tests.

3. Can you explain the `/src/middleware/engage.ts` file? Is this like Next.js middleware in that it runs with every request to every page? If so the format of putting the logic inside of `middleware` folder is new to me.

**Comment by thomas-desmond** [comment]
```
      const currentPrompt = data.results.find((p: IPrompt) => p.start === true);

      if (currentPrompt !== undefined) {
        setCurrentPrompt(currentPrompt);

        await tracker.TrackPageView(
          { page: '/prompts', channel: 'WEB', language: 'EN', currency: 'USD' },
          { prompt: currentPrompt?.id }
        );
```

Actually, looking at this code closer, it needs a variable name change, at least. The `const currentPrompt` is confusing because we already have a `currentPrompt` in the file from `  const [currentPrompt, setCurrentPrompt] = useState<IPrompt | undefined>();`  The asynchronous problem is mitigated if you use `currentPrompt` from the first line in the snippet above, which I THINK the code is referencing. But it's confusing overloading the `currentPrompt` variable.

**Comment by dylanyoung-dev** [comment]
> ```
>       const currentPrompt = data.results.find((p: IPrompt) => p.start === true);
> 
>       if (currentPrompt !== undefined) {
>         setCurrentPrompt(currentPrompt);
> 
>         await tracker.TrackPageView(
>           { page: '/prompts', channel: 'WEB', language: 'EN', currency: 'USD' },
>           { prompt: currentPrompt?.id }
>         );
> ```
> 
> Actually, looking at this code closer, it needs a variable name change, at least. The `const currentPrompt` is confusing because we already have a `currentPrompt` in the file from ` const [currentPrompt, setCurrentPrompt] = useState<IPrompt | undefined>();` The asynchronous problem is mitigated if you use `currentPrompt` from the first line in the snippet above, which I THINK the code is referencing. But it's confusing overloading the `currentPrompt` variable.

Wow yeah, someone (probably me) didn't realize that the useState had a variable with the same name.  I've updated that to call that variable nextPrompt instead.  So setCurrentPrompt is called the set variable on the useState hook, which is async.  Not sure how this funky code wasn't blowing up, should be resolved.  So there should be two calls to track the page view, one is when loading all prompts and setting the initial prompt and then the other is on line 87, which is done when the next prompt is calculated based on the prompts already completed and the items remaining in the questions queue.

> 2\. This is more because I don't know CDP well enough, but is the tracking turned off for dev/staging environment? Ideally we only track production events. Especially if we start running automated tests.

There are environment variables that will enable the tracker.  But good to bring up, because I have not properly tested what happens if those environment variables are not set.  Really just want to not run the tracking in those cases.  And that will be how we would likely run in dev/test/qa etc.

Also we are using our CDP tenant in DevRel, but eventually we'd probably want to use the Sitecore.com tenant.  

> 3\. Can you explain the /src/middleware/engage.ts file? Is this like Next.js middleware in that it runs with every request to every page? If so the format of putting the logic inside of middleware folder is new to me.

Yes just a next.js middleware that creates the engage cookie server-side vs client side, which I went with that approach (because I could've done this with client side cookies too) because they are typically more secure and less vulnerable to tampering or malicious attacks.  Now that I'm googling where the middleware goes based on Next.js, I see why you are asking this.  I was assuming you could place them anywhere, because putting them in a folder is what JSS does: https://github.com/Sitecore/jss/tree/dev/packages/sitecore-jss-nextjs/src/middleware.  Not sure how that works there.  Though I'm not sure it's not working here, since it seems to work.  I'll look into this more on Monday.

**Comment by thomas-desmond** [comment]
> So there should be two calls to track the page view, one is when loading all prompts and setting the initial prompt and then the other is on line 87, which is done when the next prompt is calculated based on the prompts already completed and the items remaining in the questions queue.

I'm a little confused here. I see the change for line 64 `TrackPageView` and I like that but shouldn't line 87 be updated as well to reference `nextPrompt` instead of `currentPrompt` to ensure we aren't using an outdated `currentPrompt` on line 89? 



For the middleware, if it works, then it works and I'm fine with it. It's hard to keep up with all the different practices you can use in Next.js but the idea of having middleware compartmentalized into files by feature is nice.

**Comment by dylanyoung-dev** [comment]
> I'm a little confused here. I see the change for line 64 `TrackPageView` and I like that but shouldn't line 87 be updated as well to reference `nextPrompt` instead of `currentPrompt` to ensure we aren't using an outdated `currentPrompt` on line 89?
> 
> For the middleware, if it works, then it works and I'm fine with it. It's hard to keep up with all the different practices you can use in Next.js but the idea of having middleware compartmentalized into files by feature is nice.

Ahh yes, sorry maybe I shouldn't code on fridays.  But yes it should be using on line 89 nextPrompt instead of current prompt, although technically it may still work, because I am setting the current prompt to next prompt above that.  Although then that could theoretically run into the async issues with the value not updating, so it's better here to use nextPrompt.  That should now be fixed.

**Comment by dylanyoung-dev** [comment]
As for the middleware, I'm scratching that, because I don't think I understand the docs on how that even works.  Turns out I was doing Client Side Cookies all along, so I just removed that middle ware.  I thought you could create server side cookies and use them locally on the client side, but I'm not so sure anymore, and what I saw on JSS, I think they use a folder to contain the middlewares and then pull them in on the middleware.ts.  Could do that, but no need now. 

As for the .env variable, I've fixed that to do a check when initializing the provider to see if env variables are used.  If they aren't it sets a flag that then will disable any future requests in the custom hook.  Also added a new AppConfig object that contains the `.env` variables so they are easier to call in the future.

I believe that should now resolve all the issues.

**Comment by thomas-desmond** [comment]
Changes look good BUT one last question, you have the note above "Need to implement a cookie notice/disclaimer". Does that mean if this code gets merged, we should not share the page link until we have the disclaimer? I'd put implementing a disclaimer as a top priority if that's the case.

**Comment by dylanyoung-dev** [comment]
Yes, good point, and not sure what to do about that.  It should have the cookie disclaimer, and was planning to copy what was done on the developer portal, but still waiting for Mark's follow up, and then I also noticed I no longer see it on the developer portal.  So now I'm wondering if copying that, is a good idea, and maybe we should look into copying what was done on Sitecore.com instead.  

Maybe we could complete the merge, and just wait to turn it on (by not applying the environment variables to Vercel) until we have the disclaimer worked out.  

I would like to have the basic tracking in MVP 3.0, and we can work toward it, but I'm not sure if we can do that or not.  I added a card to miro to the right of the board, signaling this is a really nice, nice to have.  I'll follow up with Mark and possibly message the Sitecore.com team as well to see what they are using.

**Pull request merged**
