### PR TITLE
Feature/hexagon links to devportal

### PR DESCRIPTION
**Pull request by dylanyoung-dev**
Implemented Hexagons with Popovers to show a short description with a link to the developer portal.  This change includes:

- Created a Generalized Products array of all our products and information for these products (to be used for these hexagons and other purposes in the future.  Chose to store statically vs in CH1, because this information will not change frequently.
- Added a new model to represent this data
- Added Popover functionality to the Hexagon component.
- Moved props from HexagonItem and store in the Products array now
- Made sure this component works well with Mobile (though some adjustments may still be recommended)

### CODE REVIEW

**Review by thomas-desmond — COMMENTED** [review]
Functionality looks and mobile looks fine.

My only concern is that the Hexagons don't really look like buttons that users can/should click. Not a blocker but would like your opinion, do you think it's worth it to add a hover effect to make the clickability stand out? Or do something else to make it more enticing to click? The cursor does change so that's at least one indication.

**Comment by dylanyoung-dev** [comment]
Maybe change the color slightly when you hover over them you mean?  I do change the pointer to a click pointer, but I could see if we can change the colors as well.  Let me play around with that, this afternoon.

**Comment by dylanyoung-dev** [comment]
Just spent over an hour trying to change the color, it's more complex because the button doesn't handle the styling of the hexagon, but an inner box does.  And doing group hover, I could not get that to work.  Only thing I seem to be able to do is do opacity and make the hexagon lighter and transparent.  Do you think that might be enough? Or maybe someone on the team, like mark who originally built these on the Developer portal, can have a look? maybe?

**Review by thomas-desmond — APPROVED** [review]
That's fine. If it isn't easy we don't need to spend time on it now. Approved for merge

**Pull request merged**
