### PR TITLE
Show Hosting Alternatives content if desired framework is Next.js

### PR DESCRIPTION
**Pull request by thomas-desmond**
If the visitor chooses Next.js as their desired framework Hosting Alternatives content will show

### CODE REVIEW

**Comment by dylanyoung-dev** [comment]
I'm not seeing this listed on the Fantasy outcome page (which looks awful btw).  Though when I look at the previous answers, it almost looks like it's got an issue, because I didn't select two shields (or desired languages), but just one (next.js), and I double checked by retaking the exam, and its still showing two options.  So maybe a weird bug here.

**Comment by thomas-desmond** [comment]
I agree the Fantasy outcome page does not look good. 

BUT for this PR, for at least the path I am taking I do see the correct previous answers, but I made the exact same choices in corporate and fantasy and got different outcome pages. It's hard to tell but Fantasy and Corporate do have the exact same choices but different outcomes. 

I'll start in the outcome generator code to investigate this. 

image
image

**Comment by dylanyoung-dev** [comment]
I wonder if maybe this is a content issue, that the prompts for Fantasy have their prompt options mixed up.  I'd say for this, since it's not caused by your code (or unlikely), you could see if it's an easy fix, but if not, complete this ticket and log a new bug for this issue.

**Comment by thomas-desmond** [comment]
Does looks like the CH1 changes fixed the fantasy path so selecting Next.js as a desired framework causes the correct data to display in the outcome page. 

If you approve I'll get this merged in!

**Review by dylanyoung-dev — APPROVED** [review]

**Pull request merged**
