### PR TITLE
Color palette

### PR DESCRIPTION
**Pull request by thomas-desmond**
I added a new charcoal card variant and used that for the Role and Product Recommendations cards. 

image

### CODE REVIEW

**Review by jst-cyr — CHANGES_REQUESTED** [review]
I noticed a few issues while going through this. I took a path to make sure all products were selected, and this is how it shows: 
image

**Issues noticed:**
1. The 'Send' icon and text seems to be off center
2. The 'glow' looks good on the violet, but is completely unnoticeable on the teal, and faint on the red. I think we'd want the design team to comment on this.

Overall, I think this is a positive bonus to what we have today, but I'm marking as "Request changes" so we can decide if we want to address these here, or do a roll forward and log separate GitHub issues for these items to be prioritized separately.

**Comment by thomas-desmond** [comment]
@jst-cyr Can you re-review when you have the chance? 

The Send icon is centered, or there is no code to make it go off-center. 

The glow change has been removed and be done in a separate branch.

**Review by jst-cyr — CHANGES_REQUESTED** [review]
⚠ **Description modals broken**. Clicking on a product no longer shows the details about the product, only the Learn More button.

image


Strange about the Send icon, but it does seem like it's no more off than current production so let's ignore that.

**Review by jst-cyr — APPROVED** [review]
Looks good!

**Pull request merged**
