### PR TITLE
basic cookie disclaimer implementation

### PR DESCRIPTION
**Pull request by dylanyoung-dev**
Kept this simple:

- Simple Disclaimer similar to Developer Portal, but since links are broken on the developer portal, it ended up linking to the sitecore.com cookie policy.  We probably need our own at some point, but that code be iteration #2 when we need to add the ability to decline cookie tracking.
- Right now, it doesn't close, it just sticks to the bottom of the screen.  Should be responsive.

I could make it close, but that would require more effort to keep that value in a cookie or keep it in global state.  So for now, I decided to leave it there always.

### CODE REVIEW

**Comment by thomas-desmond** [comment]
I think we do need the ability to dismiss the pop-up. It looks okay on desktop but takes up too much screen space for mobile or smaller screen formats. 

Could using a library like https://www.npmjs.com/package/cookies-next reduce implementation time?

**Comment by dylanyoung-dev** [comment]
Not a bad idea, after thinking about it, maybe should just add a plugin like this here: https://www.npmjs.com/package/react-cookie-consent and then atleast it would handle all the consent/cookie functionality for it.  Only issue is getting that to work with Chakra/Theme.  Will play with this more tomorrow.

**Comment by dylanyoung-dev** [comment]
Alright added the npm package above, looks good and is a simple way to X out of the disclaimer, since the module handles the cookies.  Also may be a worthwhile plugin to continue to use, because we probably could then use the cookie to enable/disable tracking when we get to that point.  But that task will take a little longer, so will leave it for Phase two of analytics configuration.

**Review by thomas-desmond — APPROVED** [review]
Looks good! I'll approve it, but one question. 

Does this mean CDP is enabled now in production? Since we only have the "I understand" button they cannot opt out of it which is fine so we don't need the tracking on/off functionality tracking can be always on.

**Comment by dylanyoung-dev** [comment]
That's my thought, and considering the fact that this is beta software and there is a disclaimer, yes, I would turn on CDP.  But when I speak to Sitecore.com team they may tell us that this is not enough, we will see, and then in that case, we could add a disagree type functionality with this plugin.  But I would say this looks good for where we are at now.

**Pull request merged**
