### PR TITLE
Change content source

### LINKED ISSUE #13: Migration of Content + Content Types in CH1
Currently, we are adding Content and Content Types to a Test CH1 instance, and the thought process, is if this grows in popularity is that we'll have our own CH1 instance for the game, so we'll need to plan a migration strategy. I know Sebastian's Starter Kit includes some tools to help with the migration, we need to plan to include those into the repository to serialize content types and potentially a way to migrate the content.

### PR DESCRIPTION
**Pull request by jst-cyr**
**⚠If this PR is merged, Vercel will need to be updated with a new API key for delivery endpoint. ⚠**

This PR is to make the updates necessary for migrating to the new schema. Because the new instance has slightly different type names and field names, some changes have been made to the codebase to accommodate these in the queries.

The Cypress tests are now configured to use a v2 API Key that points to the new tenant Preview endpoint. Vercel is configured to have a preview endpoint API key tied specifically to this branch. 

While in there, a few other issues were fixed:
1. Code that was outputting Personas and Avatars JSON to the console has been removed.
2. Application will now throw an error when no enabled themes are returned by the service
3. Removed console write from the ThemeService as well that was outputting data to the log.

Fixes #13

### CODE REVIEW

**Comment by dylanyoung-dev** [comment]
Looks like an issue with the Bolded question is missing?  Was that intentional?

**Comment by jst-cyr** [comment]
Definitely not expected. Let me look into what is happening there.

**Comment by jst-cyr** [comment]
@dylanyoung-dev : It was a mismatch between the new schema/GraphQL and the IPrompt property. Would be nice if applications didn't fail quite so nicely :D. That particular issue should be resolved now.

**Review by thomas-desmond — APPROVED** [review]
This looks like a clean change to me. Everything worked for me on the preview branch. 

I like the idea of this going live with the method we talked about yesterday.  Change `component.yml` & `e2e.yml` back to original variables, change Vercel secrets, change GitHub secrets, merge into main. 

We may have an issue with tests not passing once changing the yml files but we can deal with that.

**Review by dylanyoung-dev — APPROVED** [review]
Just completed several rounds of tests and the only thing I found out of the ordinary is that the personas are in a different order than what is on migration.sitecore.com, but I'm not even sure if the order matters here, and if we are doing anything to sort them.  Probably just a side effect of their publish date or something like that.

As for how we deploy, the method that @thomas-desmond mentions here, sounds good.  Otherwise I'll approve this PR.

**Comment by jst-cyr** [comment]
@dylanyoung-dev : I also noticed the ordering issue, and the order we have on current production is also not the desired order. I've logged issue #124 the other day to capture this.

**Comment by jst-cyr** [comment]
I have updated from Main, updated the GitHub secret to use the Preview API Key for the new source, and rolled back the tests to use the normal API Key variable. The 'v2' variable is now gone.

All tests have passed, code is in stable state, and preview site looks good. Now moving to update Vercel environment variables before the merge.

**Pull request merged**
