### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by thomas-desmond**
This contains the new page architecture to have a landing page before going into the Settings screen with theme selection. 

A few questions around restarts and handling page refreshes or missing `gameinfocontext`. 
1. In this initial commit, the "Start Over" button takes the user back to the settings page for theme selection
2. A refresh/invalid `gameinfocontext` takes the user to the landing home page. My thought here is usually this would happen when a user tries to navigate directly to /outcome or /prompt we want to force them to the very beginning of the app. 

Does the above make sense?

### CODE REVIEW

**Comment by jst-cyr** [comment]
Added some 'marketing' content for the landing page, fleshing out the presentation. Stole an image from Sitecore.com that is used for their migration page so that we tie in with that one:  https://www.sitecore.com/knowledge-center/digital-marketing-resources/migrating-to-xm-cloud

**Comment by jst-cyr** [comment]
**NOTE:** I've sent the current preview URL over to Chris Purcell for review from a product marketing perspective. I want to make sure we are aligned on messaging.

**Comment by dylanyoung-dev** [comment]
> This contains the new page architecture to have a landing page before going into the Settings screen with theme selection.
> 
> A few questions around restarts and handling page refreshes or missing `gameinfocontext`.
> 
> 1. In this initial commit, the "Start Over" button takes the user back to the settings page for theme selection
> 2. A refresh/invalid `gameinfocontext` takes the user to the landing home page. My thought here is usually this would happen when a user tries to navigate directly to /outcome or /prompt we want to force them to the very beginning of the app.
> 
> Does the above make sense?

I believe that logic makes sense.  Game Info Context should really only suddenly go null/undefined, if someone maybe refreshes the page.  I think the GameInfoContext needs some rework in the future, but your logic above makes sense to me.

**Review by dylanyoung-dev — APPROVED** [review]
I reviewed this more from how it was implemented vs the content, so factor that into my approval.  I think it works well, so we should be able to push this through.

I did however have some suggestions (not required to be changed):

The landing page, would be great if there was a way to get back to the landing page.  This could either be a button on the app that links you back, or it could be as simple as the link taking you to the advisor, because a new tab.

**Comment by jst-cyr** [comment]
@dylanyoung-dev : Maybe we should hyperlink the Sitecore logo in the app to take you to the landing page? Or perhaps we should change the "restart" button to go all the way back to the landing page?

**Comment by jst-cyr** [comment]
@thomas-desmond : By the way, I don't think we should hold up merging based on any feedback we might get from Chris. Those content changes can definitely be done at a later date as a separate PR.

**Comment by thomas-desmond** [comment]
I think this is good to merge. I like the idea of the Sitecore logo taking you back to the landing page. That go in in a separate PR.

**Comment by jst-cyr** [comment]
I've merged this up and added a task to the Miro to track the need to link Sitecore logo back to the landing page

**Pull request merged**
