### PR TITLE
Mobile Acceptable

### PR DESCRIPTION
**Pull request by thomas-desmond**
Improvements to UI for small screens. 

I wrestled with the "Continue" button on the index page for a while but could not find a solution I liked. The button sometimes covers the text for small screens.

### CODE REVIEW

**Comment by dylanyoung-dev** [comment]
Looks good for the most part, but still a few issues remaining:

On the Settings/Homepage:
image

Fantasy Theme:
image
image
(It may be hard to tell with this screenshot but everything is being cut off the page, and likely just needs some padding on the edges)

There are still some theme inconsistencies (mainly with the corporate theme) but I assume that's still on Mark's plate.

**Comment by thomas-desmond** [comment]
Good catch on the changes; I'm working to fix those for small-screen formats.

BUT this does bring up an issue that I'm concerned about. Even now, with only two themes, we are running into problems where each theme has specific UI tweaks that need to be made for it, and they will get exponentially harder to maintain as we add more themes/content/questions. 

For example, in the Fantasy theme, there is an SVG that sits behind the text. This SVG can grow/shrink but from my understanding not get longer height-wise while staying the same width. This means the SVG responds very differently to the Corporate theme because Corporate uses just a background color that easily grows/shrinks in all directions based on the screen size. 
image
image

 

I'd like to discuss this more with @markvanaalst, but do we need to establish a rule for what can be different from theme to theme? Maybe it's a lack of understanding of chakra and responsive designs, but I see it being very difficult moving forward if each theme ends up having different elements entirely showing up on the screen.

**Comment by thomas-desmond** [comment]
I'm not entirely happy with the changes but I removed the `panel.svg` for small screen formats and went to plain background color. The SVG was never intended to be used in small screen formats and there was no squeezing it in. 

I wanted to get this mobile acceptable and also get the other fixes in that are a part of this PR. 

I'm open to making changes to this PR but also would like to consider if those changes center around the `panel.svg` for fantasy they go into a new PR. 

@dylanyoung-dev  can you re-review this PR when you have a chance? Thank you!

**Comment by dylanyoung-dev** [comment]
Eekk.  I'm seeing more issues than I was seeing before, I wonder if that's due to the merge conflicts on this branch or maybe caused by the merge of Mark's changes this morning.  If you emulate Chrome into iPhone 12 Pro, and I can see issues with the settings page, where some stuff is centered while other stuff is left aligned and looks weird.  Also tested the fantasy version, I see some of your changes, and I think it makes sense to remove the svg for smaller screen sizes, because it can help from a performance aspect as well, but the progress bar for example looks weird.  Not sure exactly what's going on there.

**Comment by thomas-desmond** [comment]
Merging in all the Blok changes, and the merge did eat up some of my changes, and I have more issues now. 

That's fine. I'll see what I can get done this afternoon. Once this PR gets in, we'll have to add "mobile acceptable" as the definition of done before other UI-related merges get in.

**Comment by thomas-desmond** [comment]
@ dylanyoung-dev I did a push and it helps make the code mobile acceptable. 

We may need to modify the idea of this PR because it's getting too big and too long-lived. If a mobile user can reasonably get to the outcome screen on both corporate and fantasy, I would like to get the PR merged. I do see plenty of UI improvements that need/could be made and I'd like to break those into separate small PRs.

During our Thursday meeting, I'd like to create cards for all the individual UI improvements we want.

**Comment by dylanyoung-dev** [comment]
I agree, I think we had a few PRs with very similar changes, especially given the fact that design changes affect alot of components etc.  It would be best to go at this more incrementally and fix the specific issue one at a time with smaller PRs.  I'm also hoping we are past any major changes to the design, except small tweaks.  That should allow us to quickly increment and get to a stable version faster.

**Comment by markvanaalst** [comment]
I pushed some commits to this PR that take care of a whole lot of responsive issues. Personally I feel that its current state is something we can use as a reasonable foundation from which we focus on smaller more focused PRs.

The biggest challenge I have been facing with Chakra and theming is the fact that we have full control over one theme and none over the other. That makes it hard sometimes to overwrite styling properties.

I definitely agree with the point mentioned earlier about dropping some of the SVGs for the mobile version! I think we should try to use the theme SVGs for distinctive elements like buttons but not for panels etcetera.

**Comment by thomas-desmond** [comment]
Nice I like your changes @markvanaalst.

I think this is ready to merge as a mobile-acceptable PR, let met see if @dylanyoung-dev  can give one final review. 

The only issue I saw was if you choose a fantasy theme on the first page the theme would apply before navigation. So the buttons would change style for a second then you'd navigate to the new page, it just felt like a weird experience as a user. Something that could be fixed in a different PR.

**Comment by dylanyoung-dev** [comment]
Yea still seeing slight adjustments needed here and there.  Let's break those down into specific tickets and address them incrementally.  I also noticed the same issue with the Theme selection.  It should switch by the time the next screen loads, but not before (ideally).  I think it's loading the next interface and since this is a spa-like app, maybe we should use the Loading animation more while these types of things are occurring, but something we can address individually.

**Pull request merged**
