### PR TITLE
Immediately make a theme change if there is only one theme

### PR DESCRIPTION
**Pull request by jst-cyr**
If only one theme is returned by the API, the Settings page should immediately skip to persona and avatar selection.

### CODE REVIEW

**Comment by jst-cyr** [comment]
The code is done, and the content is unpublished, but local and preview sites still show unpublished content. I'm going to have to add a way for us to 'disable' a theme when we don't want to delete it, but don't want it returned

**Comment by jst-cyr** [comment]
A new 'disabled' field is on the Game Theme content model. The fantasy setting now has this set to 'true'. The logic has been updated to only select Themes that are enabled, and if only one theme is available, it skips the theme selection. Also, the tests now ignore the theme selector since it is no longer visible.

**Review by thomas-desmond — APPROVED** [review]
Code looks good, works as expected. Approved!

**Comment by jst-cyr** [comment]
I've merged in the Landing page addition from the Main branch and retested. Everything looks good. Minor conflict in the test scripts for the outcomes but resolved now.

**Pull request merged**
