### PR TITLE
Replace tooltips on mobile with popover

### PR DESCRIPTION
**Pull request by markvanaalst**
This (draft) PR adds a replacement for tooltips when in **Fantasy mode** on mobile. 

Tooltip have been replace by the Chakra popover component which adds an information icon next to the answer option. Tapping on the icon will popup the tooltip. Tapping the icon again, or tapping outside the popover will close it.

Please consider this PR experimental and not yet ready to merge. Just want to gather some feedback on whether this is a viable replacement for the mouse-over tooltips.

@thomas-desmond @dylanyoung-dev @jst-cyr: Please have a look and use the comments for feedback.

[Preview deployment here](https://sitecore-migration-game-git-t-eb0a7e-sitecoretechnicalmarketing.vercel.app/)

### CODE REVIEW

**Comment by thomas-desmond** [comment]
Interesting idea. This is a good concept for replacing hover for small screens. I'd like to get community feedback on this and see what others think. 

A few initial comments: 
1. There is not a lot of screen real state but it would be nice if the popover did not cover the current result. I'm thinking that users will click the icon, see that it's the option they want, then be able to immediately click that option without needing to dismiss the popover. 
2. For me in the current preview deployment the SVG background for the info icon disappears when the popover is open. However this doesn't seem to the case for your gif above. 
3. I'm not see

**Review by thomas-desmond — APPROVED** [review]
No idea what the 3rd bullet was supposed to say but the other two looked done.

Approved!

**Comment by jst-cyr** [comment]
Can this be merged in and deployed now?

**Comment by jst-cyr** [comment]
I've merged the branch since there were no objections but a 👍from Dylan.

**Pull request merged**
